import { Inter } from "next/font/google";
import "./globals.css";
import { TransitionProvider } from "./components/transitionProvider";
import { LabelsProvider } from "./context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cocci Webpage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LabelsProvider>
          <TransitionProvider>{children}</TransitionProvider>
        </LabelsProvider>
      </body>
    </html>
  );
}